# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.gold_rush_service:
    class: AppBundle\Service\GoldRushService
    arguments:
      - "@app.gold_rush_repository"

  app.gold_rush_repository:
    class: AppBundle\Repository\GoldRushRepository
    arguments:
      - "@app.gold_rush_resource_factory"

  app.gold_rush_resource_factory:
    class: AppBundle\Resource\GoldRushResourceFactory

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

